### ISSUE TITLE
client error: (401) Unauthorized

### ISSUE THREAD

**Issue by actuallybc** [geoffjentry/twitteR#65]
While trying to use twitteR interactively in R Studio I got this error... "XXXXXX's" are my key and secret respectively.

> library(twitteR)
> setup_twitter_oauth("XXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
[1] "Using browser based authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 1
Error in init_oauth1.0(endpoint, app, permission = params$permission) : 
  client error: (401) Unauthorized

I would appreciate any help. I have also seen the same question on stackoverflow but no answer was given. I am running R 3.1.1 with httr 0.5.0.90 and twitteR version 1.1.8.

Thanks,

B

**Comment by lmmx** [comment]
Steps that resolved this issue for me :

* try [this httr demo](https://github.com/hadley/httr/blob/master/demo/oauth1-twitter.r)
* ensure the callback URL on your app is set to http://127.0.0.1:1410 as Hadley explains [here](https://github.com/hadley/httr/issues/156#issuecomment-68863493)
* `install.packages('httpuv')` if you can't load it with `library('httpuv')`, as was the case on my machine

**Comment by geoffjentry** [comment]
@jdeboer - check out the suggestions from @lmmx 

If that doesn't solve things and you're experiencing the same issues with httr you'll need to talk to Hadley.

**Comment by aravinthan6206** [comment]
I am able to execute the demo without any error.  I am facing problems with twitteR. If I give the callback url, then I am unable to see the page which displays the PIN. I have tried this in Chrome as well as IE. IE gives 'Page cannot be displayed' error and chrome gives 'ERR_CONNECTION_REFUSED'. If I dont give the callback url, I am able to see the PIN but run into problems in the next step. This has become kind of cyclical. Without callback url I am able to complete one extra step.

**Comment by aravinthan6206** [comment]
@geoffjentry .. I found a way to work around the problem. I created the app without giving the callback url. After entering the PIN, I modified the app settings to have http://127.0.0.1:1410 as my callback url. If I follow the above mentioned steps I was able to successfully make a connection with twitter and able to download tweets. Is there any way to make this work directly without having to modify the app settings after entering the pin? Am I having this problem due to any network issues?

**Comment by geoffjentry** [comment]
You're almost certainly seeing the same issue as #90 - I'm going to close this as the original issue has gone stale and to consolidate the conversation there

**Comment by jimenezgdavid** [comment]
Be sure to > install.packages('httpuv'). That was the issue with me.

**Comment by rakesh-roshan** [comment]
I got it fixed by manually generating access token at apps.twitter.com site and pass that as argument to the api which will force to use local authentication rather than browser authentication.

**Comment by j450h1** [comment]
Tried all the approaches above and still getting HTTP 401. I hope I don't have to implement this in Python :(

**Comment by jdeboer** [comment]
If you end up using Python, I recommend the `tweepy` module. I used it recently and found it to be quite easy. If it help, you can access Python from R or the other way around if you like.

**Comment by j450h1** [comment]
Thanks for suggestion. I just solved the issue. Both of these need to be unchecked in the app settings:

* Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url)
* Allow this application to be used to Sign in with Twitter
